// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nodusfxmpofpimpmvhjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vZHVzZnhtcG9mcGltcG12aGpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjA0NjIsImV4cCI6MjA2MDA5NjQ2Mn0.04vSxuVNsKfyK-Mm-dq-bqp8hCyC1wcWAsGUWe9WYmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);